<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Lable</name>
   <tag></tag>
   <elementGuidId>962f9b0a-e9f0-487b-b796-e0856a250119</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/h4[contains(@class,'subheader')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
